# Generated by Django 3.2 on 2021-04-18 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product_imgs/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shucks.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shucks.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shucks.color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shucks.size')),
            ],
        ),
    ]
