# Generated by Django 3.2 on 2021-04-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shucks', '0004_auto_20210419_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': '2. Brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '1.Categories'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': '3. Colors'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '5. Products'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': '6. ProductAttributes'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': '4. Sizes'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
