# Generated by Django 3.2 on 2021-04-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shucks', '0008_customer_order_orderitem_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=4000, max_digits=10),
            preserve_default=False,
        ),
    ]
